### ISSUE TITLE
使用中有内存问题

### ISSUE THREAD

**Issue by iFangcy** [netyouli/WHC_KeyboardManager#1]
使用了 WHC_KeyboradManager 的 viewController 不会销毁  😂

**Comment by netyouli** [comment]
哦对，swift版本存在这个问题，oc版本不会，明天将修复

**Comment by iFangcy** [comment]
oc 版本一样有这个问题，WHC_KeyboradManager 是一个单利又对所有的控制器都强引用了，没有释放

**Comment by netyouli** [comment]
嗯我知道数组里存了vc，这个今天修复没来得及push，网络不好，明天push

**Comment by netyouli** [comment]
感谢提醒，这个添加的vc监听内存无法释放问题已经在1.0.7版本修复了，请查看

**Comment by Woxiee** [comment]
可以增加一个 键盘与输入框间距的api吗？

**Comment by netyouli** [comment]
有，实现Configuration里的offsetBlock即可
