### ISSUE TITLE
小bug

### ISSUE THREAD

**Issue by hot-man** [netyouli/WHC_KeyboardManager#3]
我在 tableFooterView加上UITextField，在tableFooterView加上UITextView；当tableView的Rows为0或者较少时，   收起键盘后，tableView整体会向下平移。

**Comment by netyouli** [comment]
谢谢，V1.0.9版本已经修复了这个问题，请更新再看看

**Comment by hot-man** [comment]
还是有问题，不过可以把tableView滑动到正确位置。

**Comment by hot-man** [comment]
在未收起键盘的时候，push到另外一个ViewController，键盘头会一直存在，无法隐藏

**Comment by netyouli** [comment]
我提供的demo没有这样情况发生，为了减少对项目干扰你可以手动收起键盘再push，
《还是有问题，不过可以把tableView滑动到正确位置。》这个问题你可以提供一个简单重现的demo我看看吗？谢谢
