### ISSUE TITLE
nav的背景设为不透明时，输入框会被nav遮挡

### ISSUE THREAD

**Issue by KZManer** [netyouli/WHC_KeyboardManager#6]
您好，在使用中遇到以下问题：
将nav的navigationBar设置为不透明时，再使用WHC_keyboardManager的话输入框会被nav遮挡住，您给看一下是什么原因，谢谢！
[正常界面](https://github.com/GhostKZShdow/SaveImages/blob/master/unClicked.png)
[点击输入框之后界面](https://github.com/GhostKZShdow/SaveImages/blob/master/clicked.png)
[这里是代码](https://github.com/GhostKZShdow/SaveImages/blob/master/code.png)

**Comment by netyouli** [comment]
请使用最新版本的库，这个问题已经不存在了
