### ISSUE TITLE
UISearchBar使用会崩溃

### ISSUE THREAD

**Issue by xunan623** [netyouli/WHC_KeyboardManager#7]
searchBar的父视图不能加约束吗?
 [headerView.superview addConstraint:[NSLayoutConstraint constraintWithItem:headerView attribute:NSLayoutAttributeLeft relatedBy:NSLayoutRelationEqual toItem:headerView.superview attribute:NSLayoutAttributeLeft multiplier:1 constant:0]];

**Comment by netyouli** [comment]
这个问题不在本库讨论范围

**Comment by xunan623** [comment]
因为用这个库文件  导致我用UISearBar就崩溃 你说和你的库没关系,程序员都是这么解决bug的啊

**Comment by netyouli** [comment]
可以发个demo我看看
